arb-dir: lib/core/l10n
template-arb-file: app_pt.arb
output-dir: lib/core/generated
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales:
  - es
  - pt